name: build-send-templates-action
run-name: ${{ github.actor }} made a push to Templates library.
on: [push]
jobs:
  send_template:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '../../react-email-starter/'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - run: npm run export
